console.log("allghdata.js ist eingebunden!");


//Komponenten als Array
function getComponents() {
    var comps = [
        "Gewächshauskonstruktion",
        "Energieschirm/Schattierung",
        "Kulturflächen",
        "Verkaufseinrichtungen",
        "Bewässerung",
        "Düngung",
        "Belichtung",
        "Klimaregelung",
        "Kühlanlagen",
        "Spezielle Arbeitsräume",
        "Sanitärräume/Sanitäranlagen",
        "Außenanlagen",
        "Wärmeerzeugung", 
        "Wärmeausbringung",
        "Wärmespeicherung"
    ];
    return comps;
}


//Komponenten in Objektform
function getCompObj() {
    var kompObj = [{
        "nummer":1,"name": "Gewächshauskonstruktion"},{
        "nummer":2, "name": "Energieschirm/Schattierung"},{
        "nummer":3, "name": "Kulturflächen"},{
        "nummer":4, "name": "Verkaufseinrichtungen"},{
        "nummer":5, "name": "Bewässerung"},{
        "nummer":6, "name": "Düngung"},{
        "nummer":7, "name":"Belichtung"},{
        "nummer":8, "name":"Klimaregelung"},{
        "nummer":9, "name":"Kühlanlagen"},{
        "nummer":10, "name":"Spezielle Arbeitsräume"},{
        "nummer":11, "name":"Sanitärräume/Sanitäranlagen"},{
        "nummer":12, "name":"Außenanlagen"},{
        "nummer":13, "name":"Wärmeerzeugung"},{ 
        "nummer":14, "name":"Wärmeausbringung"},{
        "nummer":15, "name":"Wärmerspeicherung"
    }];
    return kompObj;
}

function testobject() {
    var data = [{"nummer":1,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":356.50,"we_einheit":"€/m²"},
    {"nummer":2,"komponente":"Wärmeausbringung","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, mittleres Preissegment)","wert":534.75,"we_einheit":"€/m²"}];
    return data;
} 


function identicalObjects(){
    var result = [{"nummer":1,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":356.50,"we_einheit":"€/m²"},
    {"nummer":1,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":356.50,"we_einheit":"€/m²"},
    {"nummer":1,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":356.50,"we_einheit":"€/m²"}];
    return result;
}

function getAllData() { 

    var data = [{"nummer":1,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":356.50,"we_einheit":"€/m²"},
    {"nummer":2,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, mittleres Preissegment)","wert":534.75,"we_einheit":"€/m²"},
    {"nummer":3,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, hohes Preissegment)","wert":1069.50,"we_einheit":"€/m²"},
    {"nummer":4,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Verkaufsgewächshaus - Breitschiff (ESG, 1/3 eingedeckt m. Sandwichpl.)","wert":446.20,"we_einheit":"€/m²"},
    {"nummer":5,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"Überdachungen, Passagen (Vorbereich, Zugangsbereich Verkaufsgewächshäuser)","wert":74.75,"we_einheit":"€/m²"},
    {"nummer":6,"komponente":"Gewächshauskonstruktion","groesse":200,"gr_einheit":"m²","position":"überdachte Freiverkaufsfläche (ohne Seitenwände, volle Schneelast)","wert":95.55,"we_einheit":"€/m²"},
    {"nummer":7,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Folientunnel (Einfachfolie)","wert":23.00,"we_einheit":"€/m²"},
    {"nummer":8,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Folienhaus (Doppelfolie PE, aufblasbar)","wert":53.19,"we_einheit":"€/m²"},
    {"nummer":9,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Folienhaus (aufrollbares Dach)","wert":66.61,"we_einheit":"€/m²"},
    {"nummer":10,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Foliengewächshaus (Doppelfolie PE, aufblasbar)","wert":71.15,"we_einheit":"€/m²"},
    {"nummer":11,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Foliengewächshaus (Spezial-Doppelfolie, aufblasbar)","wert":102.95,"we_einheit":"€/m²"},
    {"nummer":12,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Venlohaus Einfachglas","wert":80.00,"we_einheit":"€/m²"},
    {"nummer":13,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Venlohaus Spezialglas (z.B. beschichtetes oder mikrostrukturiertes Glas)","wert":101.15,"we_einheit":"€/m²"},
    {"nummer":14,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Venlohaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":93.00,"we_einheit":"€/m²"},
    {"nummer":15,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Breitschiffhaus Einfachglas","wert":113.00,"we_einheit":"€/m²"},
    {"nummer":16,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Breitschiffhaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":131.00,"we_einheit":"€/m²"},
    {"nummer":17,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Cabriogewächshaus, Einfachglas (aufklappbares Dach)","wert":100.00,"we_einheit":"€/m²"},
    {"nummer":18,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Cabriogewächshaus, Polycabonatplatten (aufklappbares Dach)","wert":106.00,"we_einheit":"€/m²"},
    {"nummer":19,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Einfachglas, Ziehharmonika)","wert":150.00,"we_einheit":"€/m²"},
    {"nummer":20,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Polycarbonat, Ziehharmonika)","wert":165.00,"we_einheit":"€/m²"},
    {"nummer":21,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, einfaches Preissegment)","wert":250.70,"we_einheit":"€/m²"},
    {"nummer":22,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, mittleres Preissegment)","wert":376.05,"we_einheit":"€/m²"},
    {"nummer":23,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Verkaufsgewächshaus, Venlo (ESG, 1/3 eingedeckt mit Sandwichplatten, hohes Preissegment)","wert":752.10,"we_einheit":"€/m²"},
    {"nummer":24,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Verkaufsgewächshaus - Breitschiff (ESG, 1/3 eingedeckt m. Sandwichpl.)","wert":316.25,"we_einheit":"€/m²"},
    {"nummer":25,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"Überdachungen, Passagen (Vorbereich, Zugangsbereich Verkaufsgewächshäuser)","wert":63.25,"we_einheit":"€/m²"},
    {"nummer":26,"komponente":"Gewächshauskonstruktion","groesse":1000,"gr_einheit":"m²","position":"überdachte Freiverkaufsfläche (ohne Seitenwände, volle Schneelast)","wert":80.00,"we_einheit":"€/m²"},
    {"nummer":27,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Folientunnel (Einfachfolie)","wert":21.01,"we_einheit":"€/m²"},
    {"nummer":28,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Folienhaus (Doppelfolie PE, aufblasbar)","wert":40.63,"we_einheit":"€/m²"},
    {"nummer":29,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Folienhaus (aufrollbares Dach)","wert":55.00,"we_einheit":"€/m²"},
    {"nummer":30,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Foliengewächshaus (Doppelfolie PE, aufblasbar)","wert":60.33,"we_einheit":"€/m²"},
    {"nummer":31,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Foliengewächshaus (Spezial-Doppelfolie, aufblasbar)","wert":89.53,"we_einheit":"€/m²"},
    {"nummer":32,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Venlohaus Einfachglas","wert":68.30,"we_einheit":"€/m²"},
    {"nummer":33,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Venlohaus Spezialglas (z.B. beschichtetes oder mikrostrukturiertes Glas)","wert":86.19,"we_einheit":"€/m²"},
    {"nummer":34,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Venlohaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":74.00,"we_einheit":"€/m²"},
    {"nummer":35,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Breitschiffhaus Einfachglas","wert":75.00,"we_einheit":"€/m²"},
    {"nummer":36,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Breitschiffhaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":89.50,"we_einheit":"€/m²"},
    {"nummer":37,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Cabriogewächshaus, Einfachglas (aufklappbares Dach)","wert":80.00,"we_einheit":"€/m²"},
    {"nummer":38,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Cabriogewächshaus, Polycabonatplatten (aufklappbares Dach)","wert":86.00,"we_einheit":"€/m²"},
    {"nummer":39,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Einfachglas, Ziehharmonika)","wert":139.14,"we_einheit":"€/m²"},
    {"nummer":40,"komponente":"Gewächshauskonstruktion","groesse":5000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Polycarbonat, Ziehharmonika)","wert":154.14,"we_einheit":"€/m²"},
    {"nummer":41,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Folientunnel (Einfachfolie)","wert":18.68,"we_einheit":"€/m²"},
    {"nummer":42,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Folienhaus (Doppelfolie PE, aufblasbar)","wert":35.86,"we_einheit":"€/m²"},
    {"nummer":43,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Folienhaus (aufrollbares Dach)","wert":50.00,"we_einheit":"€/m²"},
    {"nummer":44,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Foliengewächshaus (Doppelfolie PE, aufblasbar)","wert":50.63,"we_einheit":"€/m²"},
    {"nummer":45,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Foliengewächshaus (Spezial-Doppelfolie, aufblasbar)","wert":77.23,"we_einheit":"€/m²"},
    {"nummer":46,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Venlohaus Einfachglas","wert":55.00,"we_einheit":"€/m²"},
    {"nummer":47,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Venlohaus Spezialglas (z.B. beschichtetes oder mikrostrukturiertes Glas)","wert":70.63,"we_einheit":"€/m²"},
    {"nummer":48,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Venlohaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":60.00,"we_einheit":"€/m²"},
    {"nummer":49,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Breitschiffhaus Einfachglas","wert":55.00,"we_einheit":"€/m²"},
    {"nummer":50,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Breitschiffhaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":58.00,"we_einheit":"€/m²"},
    {"nummer":51,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Cabriogewächshaus, Einfachglas (aufklappbares Dach)","wert":70.00,"we_einheit":"€/m²"},
    {"nummer":52,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Cabriogewächshaus, Polycabonatplatten (aufklappbares Dach)","wert":76.00,"we_einheit":"€/m²"},
    {"nummer":53,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Einfachglas, Ziehharmonika)","wert":120.00,"we_einheit":"€/m²"},
    {"nummer":54,"komponente":"Gewächshauskonstruktion","groesse":10000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Polycarbonat, Ziehharmonika)","wert":135.00,"we_einheit":"€/m²"},
    {"nummer":55,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Folientunnel (Einfachfolie)","wert":16.83,"we_einheit":"€/m²"},
    {"nummer":56,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Folienhaus (Doppelfolie PE, aufblasbar)","wert":29.36,"we_einheit":"€/m²"},
    {"nummer":57,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Folienhaus (aufrollbares Dach)","wert":43.27,"we_einheit":"€/m²"},
    {"nummer":58,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Foliengewächshaus (Doppelfolie PE, aufblasbar)","wert":42.71,"we_einheit":"€/m²"},
    {"nummer":59,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Foliengewächshaus (Spezial-Doppelfolie, aufblasbar)","wert":66.71,"we_einheit":"€/m²"},
    {"nummer":60,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Venlohaus Einfachglas","wert":47.00,"we_einheit":"€/m²"},
    {"nummer":61,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Venlohaus Spezialglas (z.B. beschichtetes oder mikrostrukturiertes Glas)","wert":56.01,"we_einheit":"€/m²"},
    {"nummer":62,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Venlohaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":49.50,"we_einheit":"€/m²"},
    {"nummer":63,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Breitschiffhaus Einfachglas","wert":38.30,"we_einheit":"€/m²"},
    {"nummer":64,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Breitschiffhaus Dach Einfachglas / Stehwände Stegdoppelplatte bzw. Stegdreifachplatten","wert":38.60,"we_einheit":"€/m²"},
    {"nummer":65,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Cabriogewächshaus, Einfachglas (aufklappbares Dach)","wert":65.00,"we_einheit":"€/m²"},
    {"nummer":66,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Cabriogewächshaus, Polycabonatplatten (aufklappbares Dach)","wert":71.00,"we_einheit":"€/m²"},
    {"nummer":67,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Einfachglas, Ziehharmonika)","wert":107.30,"we_einheit":"€/m²"},
    {"nummer":68,"komponente":"Gewächshauskonstruktion","groesse":40000,"gr_einheit":"m²","position":"Cabriogewächshaus (zusammenschiebbares Dach, Polycarbonat, Ziehharmonika)","wert":122.30,"we_einheit":"€/m²"},
    {"nummer":69,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"kein Energieschirm, keine Schattierung, keine Verdunkelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":70,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach) (nur ein Schirm)","wert":40.00,"we_einheit":"€/m²"},
    {"nummer":71,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (nur ein Schirm)","wert":40.00,"we_einheit":"€/m²"},
    {"nummer":72,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Verdunkelungs\Schattier \Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (doppelter Schirm)","wert":50.00,"we_einheit":"€/m²"},
    {"nummer":73,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Tagschirm (transparent)","wert":18.00,"we_einheit":"€/m²"},
    {"nummer":74,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Standard-Verkaufsgewächshausschirm (B1-Gewebe, horizontale Anbringung, Schirm auf 2/3 der Fläche)","wert":19.55,"we_einheit":"€/m²"},
    {"nummer":75,"komponente":"Energieschirm/Schattierung","groesse":200,"gr_einheit":"m²","position":"Spezial-Verkaufsgewächshausschirm (B1-Gewebe, trapezförmige Anbringung, Schirm auf 2/3 der Fläche)","wert":28.00,"we_einheit":"€/m²"},
    {"nummer":76,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"kein Energieschirm, keine Schattierung, keine Verdunkelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":77,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach) (nur ein Schirm)","wert":15.00,"we_einheit":"€/m²"},
    {"nummer":78,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (nur ein Schirm)","wert":19.00,"we_einheit":"€/m²"},
    {"nummer":79,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Verdunkelungs\Schattier \Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (doppelter Schirm)","wert":25.80,"we_einheit":"€/m²"},
    {"nummer":80,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Tagschirm (transparent)","wert":13.90,"we_einheit":"€/m²"},
    {"nummer":81,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Standard-Verkaufsgewächshausschirm (B1-Gewebe, horizontale Anbringung, Schirm auf 2/3 der Fläche)","wert":13.80,"we_einheit":"€/m²"},
    {"nummer":82,"komponente":"Energieschirm/Schattierung","groesse":1000,"gr_einheit":"m²","position":"Spezial-Verkaufsgewächshausschirm (B1-Gewebe, trapezförmige Anbringung, Schirm auf 2/3 der Fläche)","wert":23.00,"we_einheit":"€/m²"},
    {"nummer":83,"komponente":"Energieschirm/Schattierung","groesse":5000,"gr_einheit":"m²","position":"kein Energieschirm, keine Schattierung, keine Verdunkelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":84,"komponente":"Energieschirm/Schattierung","groesse":5000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach) (nur ein Schirm)","wert":10.20,"we_einheit":"€/m²"},
    {"nummer":85,"komponente":"Energieschirm/Schattierung","groesse":5000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (nur ein Schirm)","wert":12.00,"we_einheit":"€/m²"},
    {"nummer":86,"komponente":"Energieschirm/Schattierung","groesse":5000,"gr_einheit":"m²","position":"Verdunkelungs\Schattier \Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (doppelter Schirm)","wert":20.80,"we_einheit":"€/m²"},
    {"nummer":87,"komponente":"Energieschirm/Schattierung","groesse":5000,"gr_einheit":"m²","position":"Tagschirm (transparent)","wert":7.00,"we_einheit":"€/m²"},
    {"nummer":88,"komponente":"Energieschirm/Schattierung","groesse":10000,"gr_einheit":"m²","position":"kein Energieschirm, keine Schattierung, keine Verdunkelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":89,"komponente":"Energieschirm/Schattierung","groesse":10000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach) (nur ein Schirm)","wert":7.90,"we_einheit":"€/m²"},
    {"nummer":90,"komponente":"Energieschirm/Schattierung","groesse":10000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (nur ein Schirm)","wert":9.40,"we_einheit":"€/m²"},
    {"nummer":91,"komponente":"Energieschirm/Schattierung","groesse":10000,"gr_einheit":"m²","position":"Verdunkelungs\Schattier \Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (doppelter Schirm)","wert":17.70,"we_einheit":"€/m²"},
    {"nummer":92,"komponente":"Energieschirm/Schattierung","groesse":10000,"gr_einheit":"m²","position":"Tagschirm (transparent)","wert":6.65,"we_einheit":"€/m²"},
    {"nummer":93,"komponente":"Energieschirm/Schattierung","groesse":40000,"gr_einheit":"m²","position":"kein Energieschirm, keine Schattierung, keine Verdunkelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":94,"komponente":"Energieschirm/Schattierung","groesse":40000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach) (nur ein Schirm)","wert":5.00,"we_einheit":"€/m²"},
    {"nummer":95,"komponente":"Energieschirm/Schattierung","groesse":40000,"gr_einheit":"m²","position":"Schattier- und Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (nur ein Schirm)","wert":6.00,"we_einheit":"€/m²"},
    {"nummer":96,"komponente":"Energieschirm/Schattierung","groesse":40000,"gr_einheit":"m²","position":"Verdunkelungs\Schattier \Wärmedämmschirm (Dach+Seitenwände (Stehwände als Rollschirm)) (doppelter Schirm)","wert":13.50,"we_einheit":"€/m²"},
    {"nummer":97,"komponente":"Energieschirm/Schattierung","groesse":40000,"gr_einheit":"m²","position":"Tagschirm (transparent)","wert":5.00,"we_einheit":"€/m²"},
    {"nummer":98,"komponente":"Kulturflächen","groesse":200,"gr_einheit":"m²","position":"Betonfläche, -wege","wert":40.25,"we_einheit":"€/m²"},
    {"nummer":99,"komponente":"Kulturflächen","groesse":200,"gr_einheit":"m²","position":"Verkaufsfläche - Pur (ohne Tische, 2/3 Betonpflaster, 1/3 höherwertige Bodenbeläge)","wert":49.45,"we_einheit":"€/m²"},
    {"nummer":100,"komponente":"Kulturflächen","groesse":200,"gr_einheit":"m²","position":"Verkaufsfläche - Tische (mobile Ebbe-Fluttische auf 1/3 der Fläche, 1/3 Betonpflaster, 1/3 höherwertige Beläge)","wert":80.50,"we_einheit":"€/m²"},
    {"nummer":101,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Grundbeete","wert":4.51,"we_einheit":"€/m²"},
    {"nummer":102,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Folie)","wert":14.95,"we_einheit":"€/m²"},
    {"nummer":103,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Rinnen bzw. Sackkultur (Folie oder Profile, 1 Reihe pro m²)","wert":17.25,"we_einheit":"€/m²"},
    {"nummer":104,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Beton)","wert":42.55,"we_einheit":"€/m²"},
    {"nummer":105,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Rolltische (Kunststoffwanne)","wert":40.63,"we_einheit":"€/m²"},
    {"nummer":106,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Stationäre Tische (Kunststoffwanne)","wert":44.85,"we_einheit":"€/m²"},
    {"nummer":107,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Rinnentische (Aluminiumrinnen)","wert":49.83,"we_einheit":"€/m²"},
    {"nummer":108,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Mobiltische (Kunststoffwanne)","wert":59.23,"we_einheit":"€/m²"},
    {"nummer":109,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Betonfläche, -wege","wert":34.50,"we_einheit":"€/m²"},
    {"nummer":110,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Verkaufsfläche - Pur (ohne Tische, 2/3 Betonpflaster, 1/3 höherwertige Bodenbeläge)","wert":47.00,"we_einheit":"€/m²"},
    {"nummer":111,"komponente":"Kulturflächen","groesse":1000,"gr_einheit":"m²","position":"Verkaufsfläche - Tische (mobile Ebbe-Fluttische auf 1/3 der Fläche, 1/3 Betonpflaster, 1/3 höherwertige Beläge)","wert":66.70,"we_einheit":"€/m²"},
    {"nummer":112,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Grundbeete","wert":4.21,"we_einheit":"€/m²"},
    {"nummer":113,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Folie)","wert":14.38,"we_einheit":"€/m²"},
    {"nummer":114,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Rinnen bzw. Sackkultur (Folie oder Profile, 1 Reihe pro m²)","wert":16.15,"we_einheit":"€/m²"},
    {"nummer":115,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Beton)","wert":41.89,"we_einheit":"€/m²"},
    {"nummer":116,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Rolltische (Kunststoffwanne)","wert":37.38,"we_einheit":"€/m²"},
    {"nummer":117,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Stationäre Tische (Kunststoffwanne)","wert":41.25,"we_einheit":"€/m²"},
    {"nummer":118,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Rinnentische (Aluminiumrinnen)","wert":46.33,"we_einheit":"€/m²"},
    {"nummer":119,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Mobiltische (Kunststoffwanne)","wert":55.84,"we_einheit":"€/m²"},
    {"nummer":120,"komponente":"Kulturflächen","groesse":5000,"gr_einheit":"m²","position":"Betonfläche, -wege","wert":33.35,"we_einheit":"€/m²"},
    {"nummer":121,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Grundbeete","wert":3.98,"we_einheit":"€/m²"},
    {"nummer":122,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Folie)","wert":13.95,"we_einheit":"€/m²"},
    {"nummer":123,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Rinnen bzw. Sackkultur (Folie oder Profile, 1 Reihe pro m²)","wert":15.31,"we_einheit":"€/m²"},
    {"nummer":124,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Beton)","wert":41.40,"we_einheit":"€/m²"},
    {"nummer":125,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Rolltische (Kunststoffwanne)","wert":34.32,"we_einheit":"€/m²"},
    {"nummer":126,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Stationäre Tische (Kunststoffwanne)","wert":38.53,"we_einheit":"€/m²"},
    {"nummer":127,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Rinnentische (Aluminiumrinnen)","wert":43.70,"we_einheit":"€/m²"},
    {"nummer":128,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Mobiltische (Kunststoffwanne)","wert":53.30,"we_einheit":"€/m²"},
    {"nummer":129,"komponente":"Kulturflächen","groesse":10000,"gr_einheit":"m²","position":"Betonfläche, -wege","wert":33.35,"we_einheit":"€/m²"},
    {"nummer":130,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Grundbeete","wert":3.74,"we_einheit":"€/m²"},
    {"nummer":131,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Folie)","wert":13.47,"we_einheit":"€/m²"},
    {"nummer":132,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Rinnen bzw. Sackkultur (Folie oder Profile, 1 Reihe pro m²)","wert":14.42,"we_einheit":"€/m²"},
    {"nummer":133,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Ebbe-Flut-Boden (Beton)","wert":40.84,"we_einheit":"€/m²"},
    {"nummer":134,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Rolltische (Kunststoffwanne)","wert":32.60,"we_einheit":"€/m²"},
    {"nummer":135,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Stationäre Tische (Kunststoffwanne)","wert":35.70,"we_einheit":"€/m²"},
    {"nummer":136,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Rinnentische (Aluminiumrinnen)","wert":40.92,"we_einheit":"€/m²"},
    {"nummer":137,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Mobiltische (Kunststoffwanne)","wert":50.57,"we_einheit":"€/m²"},
    {"nummer":138,"komponente":"Kulturflächen","groesse":40000,"gr_einheit":"m²","position":"Betonfläche, -wege","wert":33.40,"we_einheit":"€/m²"},
    {"nummer":139,"komponente":"Verkaufseinrichtungen","groesse":200,"gr_einheit":"m²","position":"Keine Verkaufseinrichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":140,"komponente":"Verkaufseinrichtungen","groesse":200,"gr_einheit":"m²","position":"Einfache Verkaufseinrichtungen (einfache Regale, Stellagen etc.)","wert":63.25,"we_einheit":"€/m²"},
    {"nummer":141,"komponente":"Verkaufseinrichtungen","groesse":200,"gr_einheit":"m²","position":"Exklusive Verkaufseinrichtungen (hochwertige Einrichtung zur Warenpräsentation)","wert":230.00,"we_einheit":"€/m²"},
    {"nummer":142,"komponente":"Verkaufseinrichtungen","groesse":1000,"gr_einheit":"m²","position":"Keine Verkaufseinrichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":143,"komponente":"Verkaufseinrichtungen","groesse":1000,"gr_einheit":"m²","position":"Einfache Verkaufseinrichtungen (einfache Regale, Stellagen etc.)","wert":51.75,"we_einheit":"€/m²"},
    {"nummer":144,"komponente":"Verkaufseinrichtungen","groesse":1000,"gr_einheit":"m²","position":"Exklusive Verkaufseinrichtungen (hochwertige Einrichtung zur Warenpräsentation)","wert":188.60,"we_einheit":"€/m²"},
    {"nummer":145,"komponente":"Bewässerung","groesse":200,"gr_einheit":"m²","position":"Manuelle Gewächshausbewässerung (mit Brauseschlauch)","wert":2.30,"we_einheit":"€/m²"},
    {"nummer":146,"komponente":"Bewässerung","groesse":200,"gr_einheit":"m²","position":"Anstaubewässerung für Verkaufsgewächshäuser (Wassersteckdosen auf 1/3 der Fläche)","wert":28.75,"we_einheit":"€/m²"},
    {"nummer":147,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Düsenrohrbewässerung (ohne Rücklauf)","wert":8.23,"we_einheit":"€/m²"},
    {"nummer":148,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Tropfbewässerung (ohne Rücklauf)","wert":11.73,"we_einheit":"€/m²"},
    {"nummer":149,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Fließbewässerung (geschlossen mit Rücklauf)","wert":14.95,"we_einheit":"€/m²"},
    {"nummer":150,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Tropfbewässerung (geschlossen mit Rücklauf)","wert":17.83,"we_einheit":"€/m²"},
    {"nummer":151,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Anstausystem für Tische o.ä. (geschlossen mit Rücklauf)","wert":23.00,"we_einheit":"€/m²"},
    {"nummer":152,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Gießwagen (Arbeitsbreite 10 m) (ohne Rücklauf)","wert":27.37,"we_einheit":"€/m²"},
    {"nummer":153,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Manuelle Gewächshausbewässerung (mit Brauseschlauch)","wert":1.15,"we_einheit":"€/m²"},
    {"nummer":154,"komponente":"Bewässerung","groesse":1000,"gr_einheit":"m²","position":"Anstaubewässerung für Verkaufsgewächshäuser (Wassersteckdosen auf 1/3 der Fläche)","wert":8.05,"we_einheit":"€/m²"},
    {"nummer":155,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Anstausystem für Großflächen (Beete o.ä.) (geschlossen mit Rücklauf)","wert":4.57,"we_einheit":"€/m²"},
    {"nummer":156,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Düsenrohrbewässerung (ohne Rücklauf)","wert":4.67,"we_einheit":"€/m²"},
    {"nummer":157,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Tropfbewässerung (ohne Rücklauf)","wert":6.65,"we_einheit":"€/m²"},
    {"nummer":158,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Fließbewässerung (geschlossen mit Rücklauf)","wert":8.48,"we_einheit":"€/m²"},
    {"nummer":159,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Tropfbewässerung (geschlossen mit Rücklauf)","wert":10.11,"we_einheit":"€/m²"},
    {"nummer":160,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Anstausystem für Tische o.ä. (geschlossen mit Rücklauf)","wert":13.04,"we_einheit":"€/m²"},
    {"nummer":161,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Gießwagen (Arbeitsbreite 10 m) (ohne Rücklauf)","wert":21.29,"we_einheit":"€/m²"},
    {"nummer":162,"komponente":"Bewässerung","groesse":5000,"gr_einheit":"m²","position":"Manuelle Gewächshausbewässerung (mit Brauseschlauch)","wert":1.15,"we_einheit":"€/m²"},
    {"nummer":163,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Anstausystem für Großflächen (Beete o.ä.) (geschlossen mit Rücklauf)","wert":3.20,"we_einheit":"€/m²"},
    {"nummer":164,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Düsenrohrbewässerung (ohne Rücklauf)","wert":3.27,"we_einheit":"€/m²"},
    {"nummer":165,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Tropfbewässerung (ohne Rücklauf)","wert":4.65,"we_einheit":"€/m²"},
    {"nummer":166,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Fließbewässerung (geschlossen mit Rücklauf)","wert":5.92,"we_einheit":"€/m²"},
    {"nummer":167,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Tropfbewässerung (geschlossen mit Rücklauf)","wert":7.07,"we_einheit":"€/m²"},
    {"nummer":168,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Anstausystem für Tische o.ä. (geschlossen mit Rücklauf)","wert":9.12,"we_einheit":"€/m²"},
    {"nummer":169,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Gießwagen (Arbeitsbreite 10 m) (ohne Rücklauf)","wert":13.69,"we_einheit":"€/m²"},
    {"nummer":170,"komponente":"Bewässerung","groesse":10000,"gr_einheit":"m²","position":"Manuelle Gewächshausbewässerung (mit Brauseschlauch)","wert":1.15,"we_einheit":"€/m²"},
    {"nummer":171,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Anstausystem für Großflächen (Beete o.ä.) (geschlossen mit Rücklauf)","wert":2.21,"we_einheit":"€/m²"},
    {"nummer":172,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Düsenrohrbewässerung (ohne Rücklauf)","wert":2.26,"we_einheit":"€/m²"},
    {"nummer":173,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Tropfbewässerung (ohne Rücklauf)","wert":3.21,"we_einheit":"€/m²"},
    {"nummer":174,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Fließbewässerung (geschlossen mit Rücklauf)","wert":4.09,"we_einheit":"€/m²"},
    {"nummer":175,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Tropfbewässerung (geschlossen mit Rücklauf)","wert":4.89,"we_einheit":"€/m²"},
    {"nummer":176,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Anstausystem für Tische o.ä. (geschlossen mit Rücklauf)","wert":6.30,"we_einheit":"€/m²"},
    {"nummer":177,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Gießwagen (Arbeitsbreite 10 m) (ohne Rücklauf)","wert":9.45,"we_einheit":"€/m²"},
    {"nummer":178,"komponente":"Bewässerung","groesse":40000,"gr_einheit":"m²","position":"Manuelle Gewächshausbewässerung (mit Brauseschlauch)","wert":1.20,"we_einheit":"€/m²"},
    {"nummer":179,"komponente":"Düngung","groesse":200,"gr_einheit":"m²","position":"einfache Düngerdosierung (Düngermischer) (1, 3 oder 5 Stück. Je nach Gewächshausgröße)","wert":8.05,"we_einheit":"€/m²"},
    {"nummer":180,"komponente":"Düngung","groesse":200,"gr_einheit":"m²","position":"vollautomatische Düngestation mit Überwachung [1 pro Betrieb]","wert":120.75,"we_einheit":"€/m²"},
    {"nummer":181,"komponente":"Düngung","groesse":1000,"gr_einheit":"m²","position":"einfache Düngerdosierung (Düngermischer) (1, 3 oder 5 Stück. Je nach Gewächshausgröße)","wert":1.60,"we_einheit":"€/m²"},
    {"nummer":182,"komponente":"Düngung","groesse":1000,"gr_einheit":"m²","position":"vollautomatische Düngestation mit Überwachung [1 pro Betrieb]","wert":24.15,"we_einheit":"€/m²"},
    {"nummer":183,"komponente":"Düngung","groesse":5000,"gr_einheit":"m²","position":"einfache Düngerdosierung (Düngermischer) (1, 3 oder 5 Stück. Je nach Gewächshausgröße)","wert":0.95,"we_einheit":"€/m²"},
    {"nummer":184,"komponente":"Düngung","groesse":5000,"gr_einheit":"m²","position":"vollautomatische Düngestation mit Überwachung [1 pro Betrieb]","wert":4.80,"we_einheit":"€/m²"},
    {"nummer":185,"komponente":"Düngung","groesse":10000,"gr_einheit":"m²","position":"einfache Düngerdosierung (Düngermischer) (1, 3 oder 5 Stück. Je nach Gewächshausgröße)","wert":0.79,"we_einheit":"€/m²"},
    {"nummer":186,"komponente":"Düngung","groesse":10000,"gr_einheit":"m²","position":"vollautomatische Düngestation mit Überwachung [1 pro Betrieb]","wert":2.42,"we_einheit":"€/m²"},
    {"nummer":187,"komponente":"Düngung","groesse":40000,"gr_einheit":"m²","position":"einfache Düngerdosierung (Düngermischer) (1, 3 oder 5 Stück. Je nach Gewächshausgröße)","wert":null,"we_einheit":"€/m²"},
    {"nummer":188,"komponente":"Düngung","groesse":40000,"gr_einheit":"m²","position":"vollautomatische Düngestation mit Überwachung [1 pro Betrieb]","wert":2.00,"we_einheit":"€/m²"},
    {"nummer":189,"komponente":"Belichtung","groesse":200,"gr_einheit":"m²","position":"Einfache Verkaufsgrundbeleuchtung (300 Lux)","wert":35.65,"we_einheit":"€/m²"},
    {"nummer":190,"komponente":"Belichtung","groesse":200,"gr_einheit":"m²","position":"Exklusive Verkaufs/Akzentbeleuchtung (500-600 Lux)","wert":75.90,"we_einheit":"€/m²"},
    {"nummer":191,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"keine Belichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":192,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"photoperiodische Beleuchtung","wert":3.34,"we_einheit":"€/m²"},
    {"nummer":193,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (30 Welektr./m²)","wert":20.11,"we_einheit":"€/m²"},
    {"nummer":194,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (50 Welektr./m²)","wert":32.92,"we_einheit":"€/m²"},
    {"nummer":195,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (70 Welektr./m²)","wert":44.82,"we_einheit":"€/m²"},
    {"nummer":196,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Assimilationsbelichtung mit LED (50 Welektr./m2)","wert":164.62,"we_einheit":"€/m²"},
    {"nummer":197,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Einfache Verkaufsgrundbeleuchtung (300 Lux)","wert":24.15,"we_einheit":"€/m²"},
    {"nummer":198,"komponente":"Belichtung","groesse":1000,"gr_einheit":"m²","position":"Exklusive Verkaufs/Akzentbeleuchtung (500-600 Lux)","wert":50.60,"we_einheit":"€/m²"},
    {"nummer":199,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"keine Belichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":200,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"photoperiodische Beleuchtung","wert":3.16,"we_einheit":"€/m²"},
    {"nummer":201,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (30 Welektr./m²)","wert":20.11,"we_einheit":"€/m²"},
    {"nummer":202,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (50 Welektr./m²)","wert":32.92,"we_einheit":"€/m²"},
    {"nummer":203,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (70 Welektr./m²)","wert":44.82,"we_einheit":"€/m²"},
    {"nummer":204,"komponente":"Belichtung","groesse":5000,"gr_einheit":"m²","position":"Assimilationsbelichtung mit LED (50 Welektr./m2)","wert":164.62,"we_einheit":"€/m²"},
    {"nummer":205,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"keine Belichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":206,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"photoperiodische Beleuchtung","wert":2.88,"we_einheit":"€/m²"},
    {"nummer":207,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (30 Welektr./m²)","wert":20.11,"we_einheit":"€/m²"},
    {"nummer":208,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (50 Welektr./m²)","wert":32.92,"we_einheit":"€/m²"},
    {"nummer":209,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (70 Welektr./m²)","wert":44.82,"we_einheit":"€/m²"},
    {"nummer":210,"komponente":"Belichtung","groesse":10000,"gr_einheit":"m²","position":"Assimilationsbelichtung mit LED (50 Welektr./m2)","wert":164.62,"we_einheit":"€/m²"},
    {"nummer":211,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"keine Belichtung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":212,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"photoperiodische Beleuchtung","wert":2.67,"we_einheit":"€/m²"},
    {"nummer":213,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (30 Welektr./m²)","wert":20.11,"we_einheit":"€/m²"},
    {"nummer":214,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (50 Welektr./m²)","wert":32.92,"we_einheit":"€/m²"},
    {"nummer":215,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"Assimilationsbelichtung Na-Hdl. (70 Welektr./m²)","wert":44.82,"we_einheit":"€/m²"},
    {"nummer":216,"komponente":"Belichtung","groesse":40000,"gr_einheit":"m²","position":"Assimilationsbelichtung mit LED (50 Welektr./m2)","wert":164.60,"we_einheit":"€/m²"},
    {"nummer":217,"komponente":"Klimaregelung","groesse":1000,"gr_einheit":"m²","position":"keine automatische Regelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":218,"komponente":"Klimaregelung","groesse":1000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 2 Abteilungen","wert":6.06,"we_einheit":"€/m²"},
    {"nummer":219,"komponente":"Klimaregelung","groesse":1000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 6 Abteilungen","wert":15.71,"we_einheit":"€/m²"},
    {"nummer":220,"komponente":"Klimaregelung","groesse":1000,"gr_einheit":"m²","position":"Computerregelung multifunktional 2 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":16.19,"we_einheit":"€/m²"},
    {"nummer":221,"komponente":"Klimaregelung","groesse":1000,"gr_einheit":"m²","position":"Computerregelung multifunktional 6 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":26.83,"we_einheit":"€/m²"},
    {"nummer":222,"komponente":"Klimaregelung","groesse":5000,"gr_einheit":"m²","position":"keine automatische Regelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":223,"komponente":"Klimaregelung","groesse":5000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 2 Abteilungen","wert":1.30,"we_einheit":"€/m²"},
    {"nummer":224,"komponente":"Klimaregelung","groesse":5000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 6 Abteilungen","wert":3.23,"we_einheit":"€/m²"},
    {"nummer":225,"komponente":"Klimaregelung","groesse":5000,"gr_einheit":"m²","position":"Computerregelung multifunktional 2 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":3.32,"we_einheit":"€/m²"},
    {"nummer":226,"komponente":"Klimaregelung","groesse":5000,"gr_einheit":"m²","position":"Computerregelung multifunktional 6 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":5.44,"we_einheit":"€/m²"},
    {"nummer":227,"komponente":"Klimaregelung","groesse":10000,"gr_einheit":"m²","position":"keine automatische Regelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":228,"komponente":"Klimaregelung","groesse":10000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 2 Abteilungen","wert":0.70,"we_einheit":"€/m²"},
    {"nummer":229,"komponente":"Klimaregelung","groesse":10000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 6 Abteilungen","wert":1.66,"we_einheit":"€/m²"},
    {"nummer":230,"komponente":"Klimaregelung","groesse":10000,"gr_einheit":"m²","position":"Computerregelung multifunktional 2 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":1.71,"we_einheit":"€/m²"},
    {"nummer":231,"komponente":"Klimaregelung","groesse":10000,"gr_einheit":"m²","position":"Computerregelung multifunktional 6 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":2.78,"we_einheit":"€/m²"},
    {"nummer":232,"komponente":"Klimaregelung","groesse":40000,"gr_einheit":"m²","position":"keine automatische Regelung","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":233,"komponente":"Klimaregelung","groesse":40000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 2 Abteilungen","wert":0.27,"we_einheit":"€/m²"},
    {"nummer":234,"komponente":"Klimaregelung","groesse":40000,"gr_einheit":"m²","position":"Grundregelung (Heizung + Lüftung + Energieschirm) 6 Abteilungen","wert":0.52,"we_einheit":"€/m²"},
    {"nummer":235,"komponente":"Klimaregelung","groesse":40000,"gr_einheit":"m²","position":"Computerregelung multifunktional 2 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":0.53,"we_einheit":"€/m²"},
    {"nummer":236,"komponente":"Klimaregelung","groesse":40000,"gr_einheit":"m²","position":"Computerregelung multifunktional 6 Abt. (Grundregelung + Feuchte, Licht etc.)","wert":0.79,"we_einheit":"€/m²"},
    {"nummer":237,"komponente":"Kühlanlagen","groesse":10,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":238,"komponente":"Kühlanlagen","groesse":10,"gr_einheit":"m²","position":"Standardkühlzelle, Kühlraum (im Gewächshaus), 10","wert":990.00,"we_einheit":"€/m²"},
    {"nummer":239,"komponente":"Kühlanlagen","groesse":50,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":240,"komponente":"Kühlanlagen","groesse":50,"gr_einheit":"m²","position":"Standardkühlzelle, Kühlraum (im Gewächshaus), 50","wert":732.60,"we_einheit":"€/m²"},
    {"nummer":241,"komponente":"Kühlanlagen","groesse":40000,"gr_einheit":"m²","position":"keine","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":242,"komponente":"Kühlanlagen","groesse":40000,"gr_einheit":"m²","position":"Standardkühlzelle, Kühlraum (im Gewächshaus), 40000","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":243,"komponente":"Spezielle Arbeitsräume","groesse":10,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":244,"komponente":"Spezielle Arbeitsräume","groesse":10,"gr_einheit":"m²","position":"Sozialräume, Büroräume, Arbeitsräume ( leer, fest umbaut im Gewächshaus), 10","wert":495.00,"we_einheit":"€/m²"},
    {"nummer":245,"komponente":"Spezielle Arbeitsräume","groesse":50,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":246,"komponente":"Spezielle Arbeitsräume","groesse":50,"gr_einheit":"m²","position":"Sozialräume, Büroräume, Arbeitsräume ( leer, fest umbaut im Gewächshaus), 50","wert":347.60,"we_einheit":"€/m²"},
    {"nummer":247,"komponente":"Spezielle Arbeitsräume","groesse":40000,"gr_einheit":"m²","position":"keine","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":248,"komponente":"Spezielle Arbeitsräume","groesse":40000,"gr_einheit":"m²","position":"Sozialräume, Büroräume, Arbeitsräume ( leer, fest umbaut im Gewächshaus), 40000","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":249,"komponente":"Sanitärräume/Sanitäranlagen","groesse":10,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":250,"komponente":"Sanitärräume/Sanitäranlagen","groesse":10,"gr_einheit":"m²","position":"Sanitäranlagen/räume, 10","wert":1100.00,"we_einheit":"€/m²"},
    {"nummer":251,"komponente":"Sanitärräume/Sanitäranlagen","groesse":50,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":252,"komponente":"Sanitärräume/Sanitäranlagen","groesse":50,"gr_einheit":"m²","position":"Sanitäranlagen/räume, 50","wert":855.80,"we_einheit":"€/m²"},
    {"nummer":253,"komponente":"Sanitärräume/Sanitäranlagen","groesse":40000,"gr_einheit":"m²","position":"keine","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":254,"komponente":"Sanitärräume/Sanitäranlagen","groesse":40000,"gr_einheit":"m²","position":"Sanitäranlagen/räume, 40000","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":255,"komponente":"Außenanlagen","groesse":10,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":256,"komponente":"Außenanlagen","groesse":10,"gr_einheit":"m²","position":"Außenanlagen für Verkaufsgewächshäuser, 10","wert":59.40,"we_einheit":"€/m²"},
    {"nummer":257,"komponente":"Außenanlagen","groesse":50,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":258,"komponente":"Außenanlagen","groesse":50,"gr_einheit":"m²","position":"Außenanlagen für Verkaufsgewächshäuser, 50","wert":57.20,"we_einheit":"€/m²"},
    {"nummer":259,"komponente":"Außenanlagen","groesse":200,"gr_einheit":"m²","position":"keine","wert":0.00,"we_einheit":"€/m²"},
    {"nummer":260,"komponente":"Außenanlagen","groesse":200,"gr_einheit":"m²","position":"Außenanlagen für Verkaufsgewächshäuser, 200","wert":55.00,"we_einheit":"€/m²"},
    {"nummer":261,"komponente":"Außenanlagen","groesse":40000,"gr_einheit":"m²","position":"keine","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":262,"komponente":"Außenanlagen","groesse":40000,"gr_einheit":"m²","position":"Außenanlagen für Verkaufsgewächshäuser, 40000","wert":0.10,"we_einheit":"€/m²"},
    {"nummer":263,"komponente":"Wärmeausbringung","groesse":50,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":264,"komponente":"Wärmeausbringung","groesse":50,"gr_einheit":"kW","position":"Rohrbündel-Wärmetauscher (zum Laden, Entladen von Niedertemperaturwärme)","wert":844.89,"we_einheit":"€/kW"},
    {"nummer":265,"komponente":"Wärmeausbringung","groesse":50,"gr_einheit":"kW","position":"Luft/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Luftheizer, 1/3 Konvektoren)","wert":96.47,"we_einheit":"€/kW"},
    {"nummer":266,"komponente":"Wärmeausbringung","groesse":50,"gr_einheit":"kW","position":"Boden/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Bodenheizung, 1/3 Konvektoren)","wert":192.93,"we_einheit":"€/kW"},
    {"nummer":267,"komponente":"Wärmeausbringung","groesse":100,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":268,"komponente":"Wärmeausbringung","groesse":100,"gr_einheit":"kW","position":"Rohrbündel-Wärmetauscher (zum Laden, Entladen von Niedertemperaturwärme)","wert":768.50,"we_einheit":"€/kW"},
    {"nummer":269,"komponente":"Wärmeausbringung","groesse":100,"gr_einheit":"kW","position":"Luft/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Luftheizer, 1/3 Konvektoren)","wert":83.18,"we_einheit":"€/kW"},
    {"nummer":270,"komponente":"Wärmeausbringung","groesse":100,"gr_einheit":"kW","position":"Boden/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Bodenheizung, 1/3 Konvektoren)","wert":166.36,"we_einheit":"€/kW"},
    {"nummer":271,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":272,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"direkte Luftheizer","wert":46.73,"we_einheit":"€/kW"},
    {"nummer":273,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"gemischte Rohrheizung (Stahl)","wert":67.20,"we_einheit":"€/kW"},
    {"nummer":274,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Bodenheizung (in Beton) 25 % / Rohrheizung 75 %","wert":79.14,"we_einheit":"€/kW"},
    {"nummer":275,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Vegetationsheizung (Kunststoff) im Bestand 25 % / Rohrheizung 75 %","wert":80.62,"we_einheit":"€/kW"},
    {"nummer":276,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Hebe-Senkheizung (Stahl)","wert":84.77,"we_einheit":"€/kW"},
    {"nummer":277,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Rohrbündel-Wärmetauscher (zum Laden, Entladen von Niedertemperaturwärme)","wert":699.02,"we_einheit":"€/kW"},
    {"nummer":278,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Luft/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Luftheizer, 1/3 Konvektoren)","wert":71.72,"we_einheit":"€/kW"},
    {"nummer":279,"komponente":"Wärmeausbringung","groesse":500,"gr_einheit":"kW","position":"Boden/Konvektor-Heizung für Verkaufsgewächshäuser (2/3 Bodenheizung, 1/3 Konvektoren)","wert":143.45,"we_einheit":"€/kW"},
    {"nummer":280,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":281,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"direkte Luftheizer","wert":42.55,"we_einheit":"€/kW"},
    {"nummer":282,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"gemischte Rohrheizung (Stahl)","wert":56.98,"we_einheit":"€/kW"},
    {"nummer":283,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"Bodenheizung (in Beton) 25 % / Rohrheizung 75 %","wert":71.48,"we_einheit":"€/kW"},
    {"nummer":284,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"Vegetationsheizung (Kunststoff) im Bestand 25 % / Rohrheizung 75 %","wert":72.93,"we_einheit":"€/kW"},
    {"nummer":285,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"Hebe-Senkheizung (Stahl)","wert":73.32,"we_einheit":"€/kW"},
    {"nummer":286,"komponente":"Wärmeausbringung","groesse":1000,"gr_einheit":"kW","position":"Rohrbündel-Wärmetauscher (zum Laden, Entladen von Niedertemperaturwärme)","wert":635.82,"we_einheit":"€/kW"},
    {"nummer":287,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":288,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"direkte Luftheizer","wert":37.00,"we_einheit":"€/kW"},
    {"nummer":289,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"gemischte Rohrheizung (Stahl)","wert":49.52,"we_einheit":"€/kW"},
    {"nummer":290,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"Bodenheizung (in Beton) 25 % / Rohrheizung 75 %","wert":62.20,"we_einheit":"€/kW"},
    {"nummer":291,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"Vegetationsheizung (Kunststoff) im Bestand 25 % / Rohrheizung 75 %","wert":63.40,"we_einheit":"€/kW"},
    {"nummer":292,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"Hebe-Senkheizung (Stahl)","wert":63.80,"we_einheit":"€/kW"},
    {"nummer":293,"komponente":"Wärmeausbringung","groesse":5000,"gr_einheit":"kW","position":"Rohrbündel-Wärmetauscher (zum Laden, Entladen von Niedertemperaturwärme)","wert":552.90,"we_einheit":"€/kW"},
    {"nummer":294,"komponente":"Wärmeerzeugung","groesse":50,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":295,"komponente":"Wärmeerzeugung","groesse":50,"gr_einheit":"kW","position":"Wärmetauscher (für Abwärme, Fernwärme, Fremdwärme)","wert":7.70,"we_einheit":"€/kW"},
    {"nummer":296,"komponente":"Wärmeerzeugung","groesse":50,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Einkesselanlage","wert":159.85,"we_einheit":"€/kW"},
    {"nummer":297,"komponente":"Wärmeerzeugung","groesse":50,"gr_einheit":"kW","position":"Öl, Einkesselanlage","wert":169.05,"we_einheit":"€/kW"},
    {"nummer":298,"komponente":"Wärmeerzeugung","groesse":100,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":299,"komponente":"Wärmeerzeugung","groesse":100,"gr_einheit":"kW","position":"Wärmetauscher (für Abwärme, Fernwärme, Fremdwärme)","wert":6.90,"we_einheit":"€/kW"},
    {"nummer":300,"komponente":"Wärmeerzeugung","groesse":100,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Einkesselanlage","wert":158.92,"we_einheit":"€/kW"},
    {"nummer":301,"komponente":"Wärmeerzeugung","groesse":100,"gr_einheit":"kW","position":"Öl, Einkesselanlage","wert":168.01,"we_einheit":"€/kW"},
    {"nummer":302,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":303,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Wärmetauscher (für Abwärme, Fernwärme, Fremdwärme)","wert":6.16,"we_einheit":"€/kW"},
    {"nummer":304,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Einkesselanlage","wert":139.60,"we_einheit":"€/kW"},
    {"nummer":305,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Öl, Einkesselanlage","wert":148.81,"we_einheit":"€/kW"},
    {"nummer":306,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Zweikesselanlage, beide Kessel gleich groß","wert":160.51,"we_einheit":"€/kW"},
    {"nummer":307,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Einkesselanlage","wert":200.26,"we_einheit":"€/kW"},
    {"nummer":308,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Öl, Zweikesselanlage, beide Kessel gleich groß","wert":176.77,"we_einheit":"€/kW"},
    {"nummer":309,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Zweikesselanlage, beide Kessel gleich groß","wert":198.41,"we_einheit":"€/kW"},
    {"nummer":310,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Kohle/Öl Zweikesselanlage, beide Kessel gleich groß","wert":217.53,"we_einheit":"€/kW"},
    {"nummer":311,"komponente":"Wärmeerzeugung","groesse":500,"gr_einheit":"kW","position":"Holz/Öl Zweikesselanlage, beide Kessel gleich groß","wert":258.10,"we_einheit":"€/kW"},
    {"nummer":312,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":313,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Wärmetauscher (für Abwärme, Fernwärme, Fremdwärme)","wert":5.50,"we_einheit":"€/kW"},
    {"nummer":314,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Einkesselanlage","wert":114.39,"we_einheit":"€/kW"},
    {"nummer":315,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Öl, Einkesselanlage","wert":123.85,"we_einheit":"€/kW"},
    {"nummer":316,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Zweikesselanlage, beide Kessel gleich groß","wert":128.54,"we_einheit":"€/kW"},
    {"nummer":317,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Einkesselanlage","wert":140.21,"we_einheit":"€/kW"},
    {"nummer":318,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Öl, Zweikesselanlage, beide Kessel gleich groß","wert":144.11,"we_einheit":"€/kW"},
    {"nummer":319,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Zweikesselanlage, beide Kessel gleich groß","wert":160.35,"we_einheit":"€/kW"},
    {"nummer":320,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Kohle/Öl Zweikesselanlage, beide Kessel gleich groß","wert":177.00,"we_einheit":"€/kW"},
    {"nummer":321,"komponente":"Wärmeerzeugung","groesse":1000,"gr_einheit":"kW","position":"Holz/Öl Zweikesselanlage, beide Kessel gleich groß","wert":213.40,"we_einheit":"€/kW"},
    {"nummer":322,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"keine Heizung","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":323,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Wärmetauscher (für Abwärme, Fernwärme, Fremdwärme)","wert":4.90,"we_einheit":"€/kW"},
    {"nummer":324,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Einkesselanlage","wert":102.35,"we_einheit":"€/kW"},
    {"nummer":325,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Öl, Einkesselanlage","wert":110.60,"we_einheit":"€/kW"},
    {"nummer":326,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Erdgas, Brennwert mit Abgaswärmetauscher, Zweikesselanlage, beide Kessel gleich groß","wert":114.80,"we_einheit":"€/kW"},
    {"nummer":327,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Einkesselanlage","wert":125.20,"we_einheit":"€/kW"},
    {"nummer":328,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Öl, Zweikesselanlage, beide Kessel gleich groß","wert":128.70,"we_einheit":"€/kW"},
    {"nummer":329,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Öl/Erdgas (Mehrstoffbrennereinsatz), Zweikesselanlage, beide Kessel gleich groß","wert":143.20,"we_einheit":"€/kW"},
    {"nummer":330,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Kohle/Öl Zweikesselanlage, beide Kessel gleich groß","wert":280.70,"we_einheit":"€/kW"},
    {"nummer":331,"komponente":"Wärmeerzeugung","groesse":5000,"gr_einheit":"kW","position":"Holz/Öl Zweikesselanlage, beide Kessel gleich groß","wert":329.50,"we_einheit":"€/kW"},
    {"nummer":332,"komponente":"Wärmespeicherung","groesse":50,"gr_einheit":"kW","position":"kein Speicher","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":333,"komponente":"Wärmespeicherung","groesse":50,"gr_einheit":"kW","position":"konventioneller Pufferspeicher (Wasser)","wert":113.90,"we_einheit":"€/kW"},
    {"nummer":334,"komponente":"Wärmespeicherung","groesse":50,"gr_einheit":"kW","position":"Luft- Schotterspeicher (Low-tech-Version für Niedertemperaturwärme)","wert":333.41,"we_einheit":"€/kW"},
    {"nummer":335,"komponente":"Wärmespeicherung","groesse":50,"gr_einheit":"kW","position":"Wasser-Wärmespeicher + Wärmepumpe (High-tech-Version für Niedertemperaturwärme)","wert":1112.37,"we_einheit":"€/kW"},
    {"nummer":336,"komponente":"Wärmespeicherung","groesse":100,"gr_einheit":"kW","position":"kein Speicher","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":337,"komponente":"Wärmespeicherung","groesse":100,"gr_einheit":"kW","position":"konventioneller Pufferspeicher (Wasser)","wert":101.10,"we_einheit":"€/kW"},
    {"nummer":338,"komponente":"Wärmespeicherung","groesse":100,"gr_einheit":"kW","position":"Luft- Schotterspeicher (Low-tech-Version für Niedertemperaturwärme)","wert":303.69,"we_einheit":"€/kW"},
    {"nummer":339,"komponente":"Wärmespeicherung","groesse":100,"gr_einheit":"kW","position":"Wasser-Wärmespeicher + Wärmepumpe (High-tech-Version für Niedertemperaturwärme)","wert":1007.00,"we_einheit":"€/kW"},
    {"nummer":340,"komponente":"Wärmespeicherung","groesse":500,"gr_einheit":"kW","position":"kein Speicher","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":341,"komponente":"Wärmespeicherung","groesse":500,"gr_einheit":"kW","position":"konventioneller Pufferspeicher (Wasser)","wert":71.40,"we_einheit":"€/kW"},
    {"nummer":342,"komponente":"Wärmespeicherung","groesse":500,"gr_einheit":"kW","position":"Luft- Schotterspeicher (Low-tech-Version für Niedertemperaturwärme)","wert":271.70,"we_einheit":"€/kW"},
    {"nummer":343,"komponente":"Wärmespeicherung","groesse":500,"gr_einheit":"kW","position":"Wasser-Wärmespeicher + Wärmepumpe (High-tech-Version für Niedertemperaturwärme)","wert":893.36,"we_einheit":"€/kW"},
    {"nummer":344,"komponente":"Wärmespeicherung","groesse":1000,"gr_einheit":"kW","position":"kein Speicher","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":345,"komponente":"Wärmespeicherung","groesse":1000,"gr_einheit":"kW","position":"konventioneller Pufferspeicher (Wasser)","wert":65.00,"we_einheit":"€/kW"},
    {"nummer":346,"komponente":"Wärmespeicherung","groesse":1000,"gr_einheit":"kW","position":"Luft- Schotterspeicher (Low-tech-Version für Niedertemperaturwärme)","wert":243.11,"we_einheit":"€/kW"},
    {"nummer":347,"komponente":"Wärmespeicherung","groesse":1000,"gr_einheit":"kW","position":"Wasser-Wärmespeicher + Wärmepumpe (High-tech-Version für Niedertemperaturwärme)","wert":810.36,"we_einheit":"€/kW"},
    {"nummer":348,"komponente":"Wärmespeicherung","groesse":5000,"gr_einheit":"kW","position":"kein Speicher","wert":0.00,"we_einheit":"€/kW"},
    {"nummer":349,"komponente":"Wärmespeicherung","groesse":5000,"gr_einheit":"kW","position":"konventioneller Pufferspeicher (Wasser)","wert":28.90,"we_einheit":"€/kW"},
    {"nummer":350,"komponente":"Wärmespeicherung","groesse":5000,"gr_einheit":"kW","position":"Luft- Schotterspeicher (Low-tech-Version für Niedertemperaturwärme)","wert":217.52,"we_einheit":"€/kW"},
    {"nummer":351,"komponente":"Wärmespeicherung","groesse":5000,"gr_einheit":"kW","position":"Wasser-Wärmespeicher + Wärmepumpe (High-tech-Version für Niedertemperaturwärme)","wert":653.40,"we_einheit":"€/kW"}];
    return data;
}